In [1]:
import numpy as np

In [3]:
x=np.array([10.9,8,4,5,3])
x

array([10.9,  8. ,  4. ,  5. ,  3. ])

In [4]:
x.mean()

6.18

In [5]:
x.sum()

30.9

In [6]:
x.cumprod()

array([  10.9,   87.2,  348.8, 1744. , 5232. ])

In [7]:
x.cumsum()

array([10.9, 18.9, 22.9, 27.9, 30.9])

In [8]:
x.all()

True

In [9]:
x.sort()

In [10]:
x

array([ 3. ,  4. ,  5. ,  8. , 10.9])

# file input output

In [14]:
import numpy as np

In [15]:
x=[1,4,9,3,5,7]

In [16]:
y=[9,8,2,3,4,8]

In [17]:
np.save('testx',x)

In [18]:
np.load('testx.npy')

array([1, 4, 9, 3, 5, 7])

In [19]:
np.savez('testxy',x,y)

In [22]:
loadxy=np.load('testxy.npz')

In [23]:
loadxy

# liner Algebar function

In [26]:
import numpy as np

In [40]:
x=np.random.randn(2,4)
x

array([[-8.90385858e-04, -1.75472431e+00,  1.01765801e+00,
         6.00498516e-01],
       [-6.25428974e-01, -1.71548261e-01,  5.05299374e-01,
        -2.61356415e-01]])

In [45]:
y=np.random.randn(4,2)
y

array([[ 1.65069969,  0.15433554],
       [-0.38713994,  2.02907222],
       [-0.04538603, -1.4506787 ],
       [-0.40522786, -2.2883151 ]])

In [46]:
x.dot(y)

array([[ 0.38832793, -6.41102438],
       [-0.88300686, -0.57957093]])

In [47]:
x.transpose()

array([[-8.90385858e-04, -6.25428974e-01],
       [-1.75472431e+00, -1.71548261e-01],
       [ 1.01765801e+00,  5.05299374e-01],
       [ 6.00498516e-01, -2.61356415e-01]])

In [48]:
x.trace()

-0.17243864705365253

# Pseudo Random number

In [49]:
import numpy as np

In [50]:
np.random.seed(7)

In [51]:
np.random.normal(size=(3,2))

array([[ 1.6905257 , -0.46593737],
       [ 0.03282016,  0.40751628],
       [-0.78892303,  0.00206557]])

# reshape method

In [52]:
import numpy as np

In [55]:
x=np.random.randn(4,5)
x

array([[-0.40522786, -2.2883151 ,  1.04939655, -0.41647432, -0.74255353],
       [ 1.07247013, -1.65107559,  0.53542936, -2.0644148 , -0.66215934],
       [-1.20421985,  1.46197563,  1.76616088, -0.32941375,  0.84073324],
       [-0.1799864 ,  0.56806189, -0.7528372 , -1.7083392 , -1.80309866]])

In [56]:
x.reshape(2,2,5)

array([[[-0.40522786, -2.2883151 ,  1.04939655, -0.41647432,
         -0.74255353],
        [ 1.07247013, -1.65107559,  0.53542936, -2.0644148 ,
         -0.66215934]],

       [[-1.20421985,  1.46197563,  1.76616088, -0.32941375,
          0.84073324],
        [-0.1799864 ,  0.56806189, -0.7528372 , -1.7083392 ,
         -1.80309866]]])

In [57]:
x.reshape((2,2,5),order='F')

array([[[-0.40522786, -2.2883151 ,  1.04939655, -0.41647432,
         -0.74255353],
        [-1.20421985,  1.46197563,  1.76616088, -0.32941375,
          0.84073324]],

       [[ 1.07247013, -1.65107559,  0.53542936, -2.0644148 ,
         -0.66215934],
        [-0.1799864 ,  0.56806189, -0.7528372 , -1.7083392 ,
         -1.80309866]]])

In [60]:
x.reshape((2,2,-1))

array([[[-0.40522786, -2.2883151 ,  1.04939655, -0.41647432,
         -0.74255353],
        [ 1.07247013, -1.65107559,  0.53542936, -2.0644148 ,
         -0.66215934]],

       [[-1.20421985,  1.46197563,  1.76616088, -0.32941375,
          0.84073324],
        [-0.1799864 ,  0.56806189, -0.7528372 , -1.7083392 ,
         -1.80309866]]])

In [61]:
x

array([[-0.40522786, -2.2883151 ,  1.04939655, -0.41647432, -0.74255353],
       [ 1.07247013, -1.65107559,  0.53542936, -2.0644148 , -0.66215934],
       [-1.20421985,  1.46197563,  1.76616088, -0.32941375,  0.84073324],
       [-0.1799864 ,  0.56806189, -0.7528372 , -1.7083392 , -1.80309866]])

In [62]:
x.ravel()

array([-0.40522786, -2.2883151 ,  1.04939655, -0.41647432, -0.74255353,
        1.07247013, -1.65107559,  0.53542936, -2.0644148 , -0.66215934,
       -1.20421985,  1.46197563,  1.76616088, -0.32941375,  0.84073324,
       -0.1799864 ,  0.56806189, -0.7528372 , -1.7083392 , -1.80309866])

In [63]:
x.flatten()

array([-0.40522786, -2.2883151 ,  1.04939655, -0.41647432, -0.74255353,
        1.07247013, -1.65107559,  0.53542936, -2.0644148 , -0.66215934,
       -1.20421985,  1.46197563,  1.76616088, -0.32941375,  0.84073324,
       -0.1799864 ,  0.56806189, -0.7528372 , -1.7083392 , -1.80309866])

# concatenate

In [68]:
import numpy as np

In [70]:
x = [[1,2,5,9],[4,6,8,7]]

In [72]:
ar1=np.array(x)
ar1

array([[1, 2, 5, 9],
       [4, 6, 8, 7]])

In [73]:
y=[[10,5,8,4],[6,5,4,8]]

In [74]:
ar2=np.array(y)
ar2

array([[10,  5,  8,  4],
       [ 6,  5,  4,  8]])

In [75]:
np.concatenate((ar1,ar2),axis=0)

array([[ 1,  2,  5,  9],
       [ 4,  6,  8,  7],
       [10,  5,  8,  4],
       [ 6,  5,  4,  8]])

In [76]:
np.concatenate((ar1,ar2),axis=1)

array([[ 1,  2,  5,  9, 10,  5,  8,  4],
       [ 4,  6,  8,  7,  6,  5,  4,  8]])

In [78]:
np.vstack((ar1,ar2))

array([[ 1,  2,  5,  9],
       [ 4,  6,  8,  7],
       [10,  5,  8,  4],
       [ 6,  5,  4,  8]])

In [79]:
np.hstack((ar1,ar2))

array([[ 1,  2,  5,  9, 10,  5,  8,  4],
       [ 4,  6,  8,  7,  6,  5,  4,  8]])

# split

In [80]:
import numpy as np

In [81]:
x

[[1, 2, 5, 9], [4, 6, 8, 7]]

In [82]:
d=np.array(x)
d

array([[1, 2, 5, 9],
       [4, 6, 8, 7]])

In [84]:
np.split(d,[2,3])

[array([[1, 2, 5, 9],
        [4, 6, 8, 7]]),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32)]